- blog/2023-08-24-pgmq_with_python/index.md
- blog/authors.yml
This is a proposal for a blog entry for tembo.io. Please have a look and let me know your comments.
> Blog entry, pgmq with python

- docs/guides/postgres-basics/basic_sql_queries.md
- docs/postgres_guides/postgres-basics/basic_sql_queries.md
I fixed a few typos in the postgres beginner guide.
> Fix typos postgres basics

- docs/tembo-cloud/scripts/issue-token.sh
I will check this doesn't cause an issue, then link to it from doc in subsequent PR
> Create interactive script to issue long-lived token

- docs/postgres_guides/postgres-basics/basic_sql_queries.md
- docs/tembo-cloud/getting_started.md
- docs/tembo-cloud/troubleshooting.md
- docs/tembo-stacks/ML.md
- docs/tembo-stacks/standard.md
Change "instance" to "cluster"
> instance to cluster

- docs/tembo-cloud/ha_replication.md
Here is a first pass at writing some documentation around our current approach to HA stacks.
fixes: [TEM-1390](https://linear.app/tembo/issue/TEM-1390/documentation-about-replicas-ha)
> Documentation about enabling HA/Replicas

- docs/tembo-stacks/local-tembo-operator.md
- use ingress (depends on a fix in a PR thats currently open)
- correct the name used to retrieve secret
> Update local operator docs

- docs/tembo-stacks/_category_.json
- docs/tembo-stacks/enterprise-llm.md
- docs/tembo-stacks/intro-to-stacks.md
- docs/tembo-stacks/local-tembo-operator.md
- docs/tembo-stacks/message-queue.md
- docs/tembo-stacks/olap.md
- docs/tembo-stacks/oltp.md
- docs/tembo-stacks/roadmap.md
- docs/tembo-stacks/standard.md
Add a section in docs explaining the why, what and how of Tembo stacks.
> Add intro to stacks section

- docs/tembo-cloud/application-services/REST-API.md
> patch appServices doc

- docs/tembo-stacks/tembo-operator-eks.md
Collaboration with @williamong68
> DRAFT - Tembo Operator on EKS Guide

- docs/tembo-cloud/postgres-configuration.md
Add API specific doc for setting postgres configuration values.
> Add postgres configuration doc

- docs/tembo-cloud/backup-and-restore.md
Adding restore procedure documentation
* Cover a simple full recovery
* Cover a PITR recovery
fixes: [TEM-1937](https://linear.app/tembo/issue/TEM-1937/docs)
> Add restore procedure documentation

- blog/2023-10-24-anonymous-dump/index.md
Someone on X asking about this, so I wanted to make this content so I could link them.
> Anonymous dump example

- blog/2023-10-31-hacking-postgres-ep6/index.md
Creating Hacking Postgres ep6 blog
> Create hacking postgres ep6 (again)

- docusaurus.config.js
- src/pages/index.tsx
Adds [ClearBit](https://clearbit.com/) tracking tag
> init clearbit

- docusaurus/docs/tembo-stacks/machine-learning.md
We can train on ARRAY, but not VECTOR data types. No need to flatten now that we aren't working with VECTOR type.
> train on array

- docusaurus/docs/postgres_guides/extension/_category_.json
- docusaurus/docs/postgres_guides/extension/aggs_for_vecs.md
- docusaurus/docs/postgres_guides/extension/argm.md
- docusaurus/docs/postgres_guides/extension/autoinc.md
- docusaurus/docs/postgres_guides/extension/bool_plperl.md
- docusaurus/docs/postgres_guides/extension/btree_gin.md
- docusaurus/docs/postgres_guides/extension/chkpass.md
- docusaurus/docs/postgres_guides/extension/citext.md
- docusaurus/docs/postgres_guides/extension/count_distinct.md
- docusaurus/docs/postgres_guides/extension/credcheck.md
- docusaurus/docs/postgres_guides/extension/cube.md
- docusaurus/docs/postgres_guides/extension/dict_int.md
- docusaurus/docs/postgres_guides/extension/earthdistance.md
- docusaurus/docs/postgres_guides/extension/pgmq.md
- docusaurus/docs/postgres_guides/extension/plr.md
- docusaurus/docs/postgres_guides/extension/random.md
Move existing extension guides from /trunk/contrib/... to /website/.../docs/postgres_guides/extension
> Move extension guides to tembo.io

- docusaurus/blog/authors.yml
> Can't even spell my own damn name!

- docusaurus/blog/2024-02-01-pgxn-architecture/index.md
@theory this fixes spacing on your final bullet list
> fix bullets

- docusaurus/docs/tembo-cloud/billing.md
This reflects the update to storage monthly pricing from https://github.com/tembo-io/mahout/pull/484. Please only merge this docs change after the linked PR gets approved.
> Update Storage Monthly Pricing in Docs

- landing/src/components/Faqs.tsx
- landing/src/components/PricingCards.astro
- landing/src/pages/pricing.astro
Made a few copy edits to the pricing page.
> Copy edits to the pricing page

- landing/src/pages/for-enterprises.astro
- Move software deployment mode out of coming soon
- Move shared control plane / private data plane to coming soon
> Swap software and private data plane deployment modes

- docusaurus/docs/tembo-stacks/olap.md
- docusaurus/docs/tembo-stacks/olap/_category_.json
- docusaurus/docs/tembo-stacks/olap/olap.md
- docusaurus/docs/tembo-stacks/olap/technical_specs.md
- landing/src/pages/blog/[...slug].astro
Add guide based on clickbench data
> add olap guide

- docusaurus/docs/tembo-cloud/application-services/custom.md
- docusaurus/docs/tembo-cloud/application-services/embeddings.md
- docusaurus/docs/tembo-cloud/application-services/graphql.md
- docusaurus/docs/tembo-cloud/application-services/rest-api.md
missing `/api/v1/` in the app services doc
> update url to platform

- src/content/docs/getting-started/getting_started.md
- src/content/docs/product/cloud/apps/connection-pooler.md
- src/content/docs/product/cloud/apps/custom.md
- src/content/docs/product/cloud/apps/embeddings.mdx
- src/content/docs/product/cloud/apps/graphql.mdx
- src/content/docs/product/cloud/apps/rest-api.mdx
- src/content/docs/product/cloud/billing.md
- src/content/docs/product/cloud/logs.md
- src/content/docs/product/cloud/metrics.md
- src/content/docs/product/cloud/troubleshooting.md
- src/pages/docs/index.astro
Very minor changes across docs to correct word case, spellings, phrasings, and occasionally insert more specific text or calls to action. More to come, this is just the first round!
> Documentation updates: First round of typo & phrasing edits

- src/content/docs/product/stacks/adding-new-stacks.mdx
- src/content/docs/product/stacks/intro-to-stacks.mdx
This PR will serve as the place for discussion about my adaptation of the Notion "Building Tembo Stacks" page into a public-facing documentation page.
I'm checking the original content in first and will apply my changes atop it in order to make reading the diff easier.
> Add "Adding New Stacks" page

- src/content/docs/getting-started/quickstarts/drizzle.md
> Add drizzle snippet

- src/content/docs/product/stacks/AI/vectordb.md
Updates some existing content in guides.
Adds guides for scheduling, embedding locations, ad-hoc updates.
Adds the technical specifications section.
> add vectordb guides

- src/content/docs/product/stacks/AI/rag.md
Update rag guide by adding some more detail and updating the example to be compatible with the new layout of github repo
> update RAG guide

- src/content/docs/product/stacks/Analytical/geospatial.md
First round of minor cleanup including typos, phrasing, & accuracy checks.
> PLAT-550 First round of cleanup to Geospatial Stack docs

- src/content/docs/getting-started/quickstarts/libpq.md
- src/content/docs/getting-started/quickstarts/php.md
- src/content/docs/getting-started/quickstarts/python.md
> Add PHP connection guide

- src/components/Toc.tsx
-   multiplied depth (returned from Astro) with constant padding
> feat(client): add toc indentation to docs, PLAT-587

- src/content/docs/product/stacks/AI/rag.md
> add prefix to model examples

- src/content/docs/product/software/tembo-self-hosted/backups.mdx
Add guide for configuring backups for Tembo Self Hosted
> Add self hosted backups guide

- src/content/docs/product/cloud/alerts.mdx
Most of the content changed was to expand on potential causes, remedies, or visibility. This usually included extra queries, longer explanations where fitting, and a couple information blocks.
I also went ahead and reformatted all queries to fit what appeared to be the style that was primarily represented elsewhere. Some minor word tweaks and revisions as well.
> Multiple revisions to alert documentation.

- src/content/docs/getting-started/quickstarts/Prisma.md
> Add Prisma example

- src/components/BasicTable.astro
- src/components/PricingCards.astro
- src/components/TabbedTable.tsx
> pricing page enterprise to self hosted.

- src/components/PricingCards.astro
- src/pages/pricing.astro
> Update self hosted tagline and bullet points.

- src/content/docs/product/cloud/apps/connection-pooler.md
- src/content/docs/product/cloud/apps/custom.md
- src/content/docs/product/stacks/Transactional/message-queue.md
Closes https://github.com/tembo-io/website/issues/537#issue-2324319016
> remove all old usages of <Tabs /> from docs 

- src/components/Footer.astro
Adds link to Mastodon to the footer on tembo.io
> Update Footer.astro with Mastodon

- src/components/ClerkButton.tsx
- src/pages/index.astro
> rm team join button in footer and update footer cta copy

- src/content/blog/2024-07-03-series-a/index.mdx
> Add links to series a blog

- src/components/NavBar.tsx
- src/pages/index.astro
> Series A Banner

- src/content/docs/product/stacks/Analytical/timeseries.md
> improve db instructions in Timeseries Stack

- src/components/Markdown.astro
- src/pages/docs/[...slug].astro
- src/pages/for-enterprises.astro
- tailwind.config.mjs
> rm quotes from <blockquote /> elements in markdown

- src/blogAuthors.ts
Just a quick adding myself to the blog authors before I push a couple of posts.
> Add myself to blog authors

- src/content/docs/product/support/overview.mdx
> Add support page

- src/content/docs/product/cloud/hobby-tier.md
> Minor language edits on hobby tier

- src/content/docs/product/stacks/Transactional/oltp.md
Changes made:
- Consistency of intro settings, Configuration, & Extensions against the Standard Stack documentation
- Consistency update of introducing “Getting Started” section based on simple CRUD style workload.
> PLAT-548 OLTP consistency updates & add Getting Started

- src/content/docs/getting-started/postgres_guides/advanced-postgres-queries-for-performance.md
Modified the following queries:
* `pg_stat_statements` to use the current `total_exec_time` column rather than `total_time` from v12 and below.
* `pg_stat_activity` to use col = expression syntax rather than (col + expression) = interval structure. Also removed unnecessary table prefixes.
* `pg_stat_user_tables` for formatting.
> Minor revision to query samples

- src/content/docs/product/stacks/AI/VectorDB/portkey.md
This PR addresses minor issues in Portkey.md guide. 
No substantial content changes were made. These updates improve readability and correctness of the document.
> Fixing issues and updating portkey.md

- src/blogAuthors.ts
Adding Ash to our list of bloggers.
> Add Ash and Amy to list of blog authors

- src/components/BootcampForm.tsx
> fix date input on /bootcamp form (webkit only)

- src/components/NavBar.tsx
Better to feature Tembo AI vs. our Series A
> Change top bar to Tembo AI

- src/components/ContactForm.tsx
- src/pages/solutions/for-enterprises.astro
> Better bottom

- src/content/docs/getting-started/postgres_guides/postgres-cache-optimization.md
- src/content/docs/product/cloud/troubleshooting/connectivity.mdx
> fix broken links

- src/components/JoinTemboCTA.astro
> CLOUD-1269: Fix CTA

- src/components/BuildcampForm.tsx
- src/pages/solutions/buildcamp.astro
> CLOUD-1258: Add Question to Buildcamp Form

- src/components/MobileMenu.tsx
> Fix Transactional Link on Mobile

- src/content/docs/product/stacks/Analytical/timeseries.md
Adds a quick IVM usage section to the timeseries guide.
> Add IVM usage section

- src/content/blog/2024-10-03-paradedb-search-analytics/index.mdx
`tsquery` was incorrect, it's `ts_vector`.
> Update paradedb post

- package-lock.json
- package.json
- src/components/Bounties.astro
- src/components/Spotlight.tsx
Added a grid of cards displaying open Tembo bounties using the [Algora SDK](https://algora.io/sdk)
```mdx
import Bounties from '../../../components/Bounties.astro';
<Bounties />
```
Number of bounties displayed can be configured in [Bounties.astro](https://github.com/zcesur/tembo-website/blob/feat/bounties/src/components/Bounties.astro)
To test it before there are open Tembo bounties, you can set `org` to `algora`
> Add Bounties component

- src/pages/index.astro
> revert footer on landing to use elephant road

- src/content/blog/2024-11-07-parade-search/index.mdx
> fix yaml formatting on frontmatter

- src/components/MobileMenu.tsx
- src/components/NavBar.tsx
> remove platform pages from nav

- src/components/Footer.astro
- src/pages/blog/[...slug].astro
- src/pages/customers/index.astro
- src/pages/index.astro
> rm border-b from /customers page
