- docusaurus.config.js
Hi there, was checking out [the docs](https://tembo.io/docs/) and noticed the "Edit this page" links weren't working, I think this should fix that!
> Use correct org name for github links

- docs/tembo-cloud/postgres_users.md
Adding in documentation around both the `postgres` and `app` user.
This might need to wait to be merged until the UI work has been completed ([TEM-1388](https://linear.app/tembo/issue/TEM-1388/add-many-connection-strings-view-in-ui-total-of-6-connection-strings))
fixes: [TEM-1388](https://linear.app/tembo/issue/TEM-1388/add-many-connection-strings-view-in-ui-total-of-6-connection-strings)
> Documentation about app user

- blog/2023-09-28-pgmq-internals/index.md
- blog/2023-10-03-clerk-fdw/index.md
It looks like by default, the post thumbnails are searched in the root directory, e.g.:
"property="og:image" content="https://tembo.io/pgmq-archive.png""
The result is something like: 
https://x.com/planetpostgres/status/1707542061157699732?s=20
I saw that other posts use "./<filename>.png" and the thumbnails of those look good, e.g.:
https://x.com/planetpostgres/status/1707768565917433991?s=20
In this PR I am updating two posts to correct the problem.
> Fix thumbnails in blog posts

- docusaurus/docs/tembo-stacks/tembo-operator-install.md
There was an issue describing how to install the Helm chart with Helm.  This PR changes the command to be the correct way to install it.
- Remove the documentation on manually installing the CRD. The issue here is that we are now using Go templating (for use with Helm) and you can no longer just install the raw CRD using `kubectl`.
- Remove the strict version of the Helm chart and make it more generic, which will always install the latest version of the Helm chart when running the command.
> Fix issue with installing tembo-operator Helm chart.

- landing/src/components/Extension.astro
- landing/src/components/HeroCard.astro
- landing/src/pages/index.astro
- Scale HeroCard font on mobile
- Scale down hero section to 75% and reduce margin + padding
- Update extension card images on mobile to just use `w-full`
> Landing hero scaling

- docusaurus/docs/tembo-stacks/vector-db.md
```
postgres=# SELECT vectorize.table(                                                                                                      job_name => 'product_search',                                                                                                       "table" => 'products',                                                                                                              primary_key => 'product_id',                                                                                                        columns => ARRAY['product_name', 'description'],                                                                                );
ERROR:  syntax error at or near ")"
LINE 6: );
^
postgres=# SELECT vectorize.table( …
```
> Fix typo in vector getting started guide

- docusaurus/docs/tembo-stacks/intro-to-stacks.md
This PR adds a link to the Geospatial Stack documentation within the table on the Introduction to Stacks page.
> Update intro to include geospatial link.

- docusaurus/docs/tembo-stacks/mongo-alternative.md
Our current recommended best practices is to treat `psql` connections as read only and the `mongosh` connections as both read and write. This PR updates our docs to reflect that.
> Update MongoAlt Stack docs best practices.

- docusaurus/docs/tembo-stacks/tembo-operator-install.md
Traefik CRDs are no longer a dependency for the tembo operator (https://github.com/tembo-io/tembo/pull/528). Dropping prerequisite from installation documentation.
> Drop Traefik prerequisite from operator installation guide

- landing/src/content/blog/2024-02-12-extension-ecosystem-jobs/index.md
I assume we don't want to fix the slug, as it would change the URL and could create duplicates downstream. :-(
> Fix description typo

- docusaurus/docs/postgres_guides/connecting-to-postgres-with-nodejs/connecting-to-postgres-with-nodejs.md
A user pointed out some bad quotes in one of our guides. This fixes them.
> Fix quotes in samples

- landing/src/content/blog/2023-09-14-four-types-of-extensions/index.mdx
- landing/src/content/blog/2023-09-28-pgmq-internals/index.mdx
I was reviewing the post for the metadata standard (good stuff here!), and noticed a bunch of `:::` annotations. Looking at the source, I see there is one thing that is display more nicely, using a `<Callout>` syntax. So switch to that syntax in this post, plus one other orphan `:::` in the Rust extension anatomy post.
> Convert wayard :::s to <Callout>s in blog posts

- docusaurus/docs/tembo-stacks/datawarehouse.md
- docusaurus/docs/tembo-stacks/geospatial.md
- docusaurus/docs/tembo-stacks/machine-learning.md
- Add image section to highlight whether a given stack uses a custom-made image, as well as a link to the source repository, [https://github.com/tembo-io/tembo-images](https://github.com/tembo-io/tembo-images)
-- geo stack updated
-- dw stack updated
-- ml stack updated
- Moved `fuzzystrmatch` to group additional supplied modules at the top of extensions section
> Update stacks docs

- src/content/docs/product/stacks/AI/machine-learning.md
The part [showing how to](https://tembo.io/docs/product/stacks/ai/machine-learning#serve-the-model-w-a-rest-api-using-postgrest) serve the model with PostgREST appears to copy/paste the previous embeddings example (thus doesn't use the `input_string` variable).
> Fix typo on machine-learning.md

- src/content/docs/product/stacks/AI/vectordb.md
Reviewed for:
- Header consistency
- Grammar / phrasing / capitalization
- Formatting
- Completeness & accuracy
Further rounds of this doc should include:
- Addition of "Configuration" section clearly detailing [what's been configured and why](https://github.com/tembo-io/tembo/blob/bbb464870101a6e310477036b1dca0b1d3c3c0eb/tembo-stacks/src/stacks/specs/vectordb.yaml#L143)
Adjacent changes to the docs should include:
- Headers past H2 should **not** be displayed in right hand side navigation. _Why?_ 
1) Level 3 and 2 headers are displayed at the same level (leads to a confusing user journey). 
2) Headers are hidden from users as a result (i.e. the important "Support" header isn't visible unless you scroll all the way to the bottom of the content).
> PLAT-549 First round of cleanup to VectorDB Stack docs

- src/content/docs/product/stacks/Transactional/mongo-alternative.md
- Cleaned up missing words / improved phrasing & flow
- Cleaned up formatting
One question:
> Once connected to the instance, running \dn will list the schemas and show ferretdb and an option.
What was originally meant here by "...and an option"? Only the schema name and owner is displayed so I'm not sure what this should represent! Let's alter it so it's more clear.
> PLAT-548 First round of cleanup to MongoAlternative Stack docs

- src/content/docs/product/stacks/Analytical/olap.md
First pass through of cleaning up typos, grammar, and inconsistency within the docs.
Two notes for later:
- Under "Load a sample dataset", the Clickhouse dataset takes a _very_ long time to download (at least for someone without great internet quality or speed). Is it possible to still make these examples work with a smaller data set?
- Something for @DarrenBaldwin07: this guide in particular you can't see "Support" as a H2 until the user has actually scrolled down the page. So when trying to quickly scan for help, a user may overlook that option. Is it a possibility or something under consideration to only show H2 headers in the right hand side nav? Can I help with it?
> PLAT-550 FIrst round of cleanup to OLAP Stack docs

- src/content/docs/getting-started/quickstarts/libpq.md
- src/content/docs/getting-started/quickstarts/sni-workaround.md
- src/content/docs/product/cloud/troubleshooting.mdx
> SNI workaround doc

- src/content/docs/getting-started/postgres_guides/postgres-cache-optimization.md
The work_mem GUC is particularly tricky because complex queries can allocate a work_mem amount of RAM for every query node in the execution plan. This can result in dozens of instances of work_mem in extreme cases, and can lead to OOM in high connection scenarios. It's one of the harder entries to tune properly, so we should be explicit on the implications and err a bit on the conservative side.
> Reworded the work_mem section for accuracy.

- src/layouts/Layout.astro
> add google analytics tag

- src/content/docs/product/software/overview.mdx
- src/content/docs/product/software/tembo-self-hosted/overview.mdx
> Remove `-` from `self-hosted`

- src/content/docs/product/cloud/configuration-and-management/increase-storage.mdx
Add documentation on how to increase storage via the API
issue: [CLOUD-645](https://linear.app/tembo/issue/CLOUD-645/after-running-out-of-storage-an-instance-cannot-recover-from)
> add documentation on how to increase storage via the API

- src/content/docs/product/software/tembo-self-hosted/backups.mdx
Add step for uploading conductor-cf-template-v2.yaml to cloud formation template bucket.
> Add step for uploading `conductor-cf-template-v2.yaml` to backups guide

- src/content/docs/development/api.md
- src/content/docs/product/cloud/security/revoke-token.mdx
> Add revoke token doc

- src/pages/index.astro
> tweak hero header spacing

- src/content/docs/product/stacks/Analytical/timeseries.md
Add instructions for running pg_timeseries in a new db
> update db instructions in Timeseries Stack

- src/pages/docs/[...slug].astro
> add margin-bottom to tags in docs footer

- src/content/docs/product/cloud/troubleshooting/alerts.mdx
Fix syntax error in lock investigation query.
> Update lock investigation query

- src/components/Footer.astro
Since we're going to move pgt.dev content to `/extensions` I don't think we need to send our visitors off to pgt.dev or promote the trunk slack
> Remove trunk links

- src/content/blog/2024-09-24-multimodal-image-search/index.mdx
> troubleshoot wikipedia image

- src/components/BlogList.astro
- src/pages/blog/atom.xml.ts
- src/pages/blog/planet-postgres-feed.xml.ts
- src/pages/customers/arch.astro
- src/pages/customers/schoolai.astro
- src/pages/solutions/buildcamp.astro
- src/pages/solutions/for-enterprises.astro
I'm assuming that Markdown is already rendered with "smartypants" mode. Probably lots more of these, but let's at least start with "Tembo’s Blog" as a page title rendering nicely, plus other instances of Tembo possessiveness.
> Use curly apostrophe in "Tembo’s"

- src/content/docs/product/cloud/troubleshooting/logs.md
From an intercom chat the user was confused about which data plane domain name to use.  Adding specific URL's for each currently supported data plane.
> Add specific URLs for data plane logs

- src/content/docs/getting-started/quickstarts/database-clients-and-tools/drizzle.md
> updating Drizzle ORM docs to include fix for error

- src/layouts/DocsLayout.astro
> hide overflow x on docs landing

- src/layouts/Layout.astro
> feat(client): add scarf pixel

- src/components/JoinTemboCTA.astro
- src/pages/pricing.astro
> fix pricing footer background color
